### ISSUE TITLE
Interpreter is not a constructor

### ISSUE THREAD

**Issue by hsluoyz** [mobily-enterprises/js-interpreter#1]
TypeError: js_interpreter_npm__WEBPACK_IMPORTED_MODULE_13___default.a is not a constructor
PlayerTask.runScript
C:/GoPath/src/github.com/xxx/web/src/tasks/PlayerTask.js:194
  191 |      interpreter.setProperty(scope, 'getFrontCount', interpreter.createNativeFunction(getFrontCountWrapper));
  192 |    };
  193 | 
> 194 |    let myInterpreter = new Interpreter(code, initFunc);
      | ^  195 |    this.setState({
  196 |      interpreter: myInterpreter,
  197 |      restarted: false,

**Comment by mercmobily** [comment]
My apologies, I have only just created this module and was in the process of testing it for the client side. I am doing it now -- it's obviously something silly I missed.

**Comment by mercmobily** [comment]
My apologies, I am having trouble reproducing this. Can you please help me? Are you building it?

**Comment by mercmobily** [comment]
...?

**Comment by hsluoyz** [comment]
Sorry for that I don't have much time to make a full example. But I think you didn't export the functions. I have finished a working interpreter based on another fork, maybe it's useful: https://github.com/hsluoyz/JS-Interpreter

**Comment by mercmobily** [comment]
You are using a fork that is some 112 commits behind the actual JS Interpreter.
I think you are experience a weird problem that only happens in some specific edge cases.
I don't do anything with JSInterpreter other than sandwitch the code with a scope to make sure that acorn is defined.

I did some research.  Would you please try adding this:

     Interpreter.default = Interpreter;

Just before the very last line of js-interpreter.js:

    }).call(scope)

And tell me if it works?

Or, according to [this post](https://ethereum.stackexchange.com/questions/62693/typeerror-web3-1-default-is-not-a-constructor):

> If using a recent web3 (e.g. 1.0.0-beta.50), a possible remedy is to set esModuleInterop:
````
{
  "compilerOptions": {
    "esModuleInterop": true
  }
}
````

This is likely a very simple issue to solve. If you prefer using an abandoned fork from 2013, all good.

**Comment by mercmobily** [comment]
Another project has a similar problem, and I asked for help: https://github.com/josdejong/jsoneditor/issues/548#issuecomment-577949861

**Comment by mercmobily** [comment]
Closing this unless it's still a problem!
