### ISSUE TITLE
update to master

### ISSUE THREAD

**Issue by Kreijstal** [mobily-enterprises/js-interpreter#2]
please update to master

**Comment by mercmobily** [comment]
Can you please give it a bit of a  test and confirm that everything still works?

**Comment by mercmobily** [comment]
@Kreijstal Can you please give it a bit of a test and confirm that everything still works? (Sorry, this was meant for you and I forgot the @)

**Comment by mercmobily** [comment]
Version 1.8 is using the absolute latest acorn/js-interpreter.

**Comment by mercmobily** [comment]
(All good?)

**Comment by Kreijstal** [comment]
I'll check

**Comment by Kreijstal** [comment]
Hi, I have checked, it seems require("js-interpreter-npm") exports an empty object {}.
I know you haven't updated this repo in quite a while, but for things like sanity checking we could implement CI, so we can check things like that just in case, I'll try also to figure out what is the problem

**Comment by Kreijstal** [comment]
wait nvm I just did the npm thing I didnt clone from this repo specifically, let me do that instead

**Comment by Kreijstal** [comment]
Okay, so I cloned from source and it turns out.
``` 
$ node
Welcome to Node.js v21.7.1.
Type ".help" for more information.
> require("./js-interpreter.js")
{}
>
``` 
It does not work like that as well.

---
I think I can fix it but I will use umd

**Comment by mercmobily** [comment]
You might be very interested in https://github.com/NeilFraser/JS-Interpreter/pull/268 and https://github.com/NeilFraser/JS-Interpreter/issues/267 I hope it will get merged.

**Comment by mercmobily** [comment]
Just writing to confirm that my pull request works really well. I published the fork as js-interpreter-esm, but I anticipate (and really hope) the pull request will be merged. If it does, the owner of npm's domain js-interpreter has given Neil his availability to be used for the official js-interpreter. So, IDEALLY, there will be one js-interpreter, the official one, which works  as browser global, CJS and ESM. Fingers crossed. I am using js-interpreter-esm on a huge production server without dramas.

**Comment by Kreijstal** [comment]
> Just writing to confirm that my pull request works really well. I published the fork as js-interpreter-esm, but I anticipate (and really hope) the pull request will be merged. If it does, the owner of npm's domain js-interpreter has given Neil his availability to be used for the official js-interpreter. So, IDEALLY, there will be one js-interpreter, the official one, which works as browser global, CJS and ESM. Fingers crossed. I am using js-interpreter-esm on a huge production server without dramas.

you shouldn't need to do that, you can put both esm and umd under the same npm package

**Comment by Kreijstal** [comment]
actually having multiple packages for the same code would be confusing

**Comment by mercmobily** [comment]
Did you look at the fork? It IS under the same package,
The npm  package js-interpreter-esm is a temporary one that includes the changes I made to Neil'ls js-interpreter waiting for them to hopefully approve my Pull Request (looks promising). js-interpreter-esm  includes all of them -- brower's namespace, CJS and ESM. Yeah, the name is not great, but I didn't want to calld it js-interpreter-pull-request...
